# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' CPP_CalValue
#' 
#' Use RCPPArmadillo to speed up calculation for 
#' inside function, do not need to export
#' @param x matrix of independent variables
#' @param y matrix of dependent variables
#' @return beta a vector of estimated coefficients
#' @return fitted_val a vector of estimated fitted value
#' @return resid_val a vector of estimated residuals
#' @return xtx a matrix calculate (X^T*X)^(-1)
#' @return df a double value represents degree of freedom
#' @useDynLib lm2, Summary_lm2
#' @export
get_Cal_val <- function(x, y) {
    .Call(`_lm2Wsmry_get_Cal_val`, x, y)
}

